# Generated by Django 4.1.5 on 2023-01-19 07:16

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='posts/images', validators=[blog.validators.validate_image_size]),
        ),
    ]
